### ISSUE TITLE
Jar Files

### ISSUE THREAD

**Issue by kphaneuf** [Esri/gtfsrealtime-for-geoevent#1]
I have, I assume, successfully installed the program.  There is only one jar file, gtfsrealtime-adapter-10.6.0.jar, in the target folder.  I have move this to the deploy folder.  When I go to add a GTFS Realtime Feed, there are no options for configuration.  It's all just blank.  See attached image.  I'm guessing there should be more jar files?  Any help would be great.  I am using 10.6.0 for both GeoEvent and my server installed on the same Windows 2012 R2 machine. 
![image](https://user-images.githubusercontent.com/13141791/43094058-c743053e-8e66-11e8-9afd-2edff7b1a653.png)

**Comment by gtieman** [comment]
Hi kphaneuf, you can download the latest 10.6 GTFS Realtime JARs (gtfsrealtime-adapter-10.6.0.jar and timetrigger-transport-10.6.0) at the Box link below.

https://esri.box.com/s/wcskao4io9lseju981sle08owl3r1nqp

Remove any previous versions of these JARs from the GeoEvent Server _deploy_ folder prior to deploying these new JARs. Then follow the steps below to get the input connector properties to appear in GeoEvent Manager.

1. In **_GeoEvent Manager_**, navigate to **_Site_** > **_Connectors_** and locate the **Receive GTFS Realtime Feed** in the list of available connectors.
2. Click the **Edit** button to open the connector properties.
3. Click **Save** to save the connector without making any changes to the properties.
4. Navigate to **_Services_** > **_Inputs_** and click **Add Input**.
5. Locate the **Receive GTFS Realtime Feed** input connector from the list and click **Select**.
6. The connector properties should now appear in _**GeoEvent Manager**_.

**Comment by kphaneuf** [comment]
Awesome! That worked.
Also, when installing in command prompt I get this warning. Not sure if it's related at all.
[WARNING] Bundle com.esri.geoevent.adapter:gtfsrealtime-adapter:bundle:10.6.0 : Did not find matching referal for !com.google.*
I've installed Maven 3.5.4 and jdk 1.8.0_181 x64.
